# Generated by Django 3.0.6 on 2020-06-01 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trading',
            name='price',
        ),
    ]
