# Generated by Django 3.0.6 on 2020-05-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_auto_20200517_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trading',
            old_name='stock',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='trading',
            name='price',
            field=models.FloatField(),
        ),
    ]
