# Generated by Django 3.0.6 on 2020-05-21 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_auto_20200517_0836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trading',
        ),
    ]
