# Generated by Django 3.0.6 on 2020-06-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
