# Generated by Django 2.2.4 on 2020-07-03 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_auto_20200626_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
