# Generated by Django 2.2.4 on 2020-07-29 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0012_auto_20200703_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=500)),
                ('linked', models.URLField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('video', models.FileField(blank=True, upload_to='')),
                ('active', models.BooleanField(default=False)),
                ('start', models.BigIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
